import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import RightNavBar from "../Components/rightNavBar";
import { SkeletonTheme } from "react-loading-skeleton";
import { Grid } from "@mui/material";
import ButtomNavBar from "@/Components/buttomNavBar";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SkeletonTheme baseColor="#dfdee2" highlightColor="#999">
          <div className="flex-row lg:flex md:flex justify-center md:px-40 lg:px-40 ">
            <div className="">
              <RightNavBar />
            </div>
            <div className="flex flex-col">
              <div className="lg:ml-[200px] md:ml-[150px]">{children}</div>
              <ButtomNavBar />
            </div>
          </div>
        </SkeletonTheme>
      </body>
    </html>
  );
}
